In [1]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))

False
tensor([[0.4350, 0.2728],
        [0.6037, 0.5422]])


In [2]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])

In [3]:
print(x)

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])


In [4]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
torch.ones(2,2) + torch.ones(2,2) # addition of tensors

tensor([[2., 2.],
        [2., 2.]])

In [8]:
torch.ones(2,2) * torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [9]:
# if you have a tensor of rank 0, you can pull out the value with item()
torch.rand(1).item()

0.4690921902656555